import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tracker de Portfolio Crypto Gratuit 2025 - Suivi Investissement Cryptomonnaies",
  description: "Tracker de portfolio crypto gratuit pour suivre vos investissements en cryptomonnaies. Gérez Bitcoin, Ethereum, BNB, Cardano, Solana et plus. Calcul automatique profits/pertes, visualisation performance, export CSV. Outil de suivi crypto simple et sécurisé.",
  keywords: [
    "tracker crypto",
    "portfolio crypto",
    "suivi crypto",
    "investissement crypto",
    "bitcoin tracker",
    "ethereum tracker",
    "portfolio bitcoin",
    "portfolio cryptomonnaie",
    "crypto portfolio tracker",
    "suivi cryptomonnaies",
    "gestion crypto",
    "tracker investissement crypto",
    "calculateur crypto",
    "profit loss crypto",
    "portfolio management crypto",
    "crypto tracker gratuit",
    "outil crypto gratuit",
    "bitcoin portfolio",
    "ethereum portfolio",
    "BNB tracker",
    "cardano tracker",
    "solana tracker",
    "XRP tracker",
    "polkadot tracker",
    "dogecoin tracker",
    "suivre ses cryptos",
    "gérer portfolio crypto",
    "investissement blockchain",
    "actifs numériques",
    "crypto assets tracker",
    "suivi investissement bitcoin",
    "calculer profit crypto",
    "performance crypto",
    "crypto français",
    "tracker crypto France",
    "fiscalité crypto France",
    "impôts crypto",
    "plus-value crypto",
    "taxation crypto",
    "wallet tracker",
    "crypto wallet",
    "export portfolio crypto",
    "crypto CSV",
    "bitcoin euro",
    "ethereum euro",
    "cours crypto",
    "prix bitcoin",
    "prix ethereum",
  ],
  alternates: {
    canonical: "/tracker-crypto",
  },
  openGraph: {
    title: "Tracker de Portfolio Crypto Gratuit - Suivez vos Investissements Crypto",
    description: "Outil gratuit pour tracker votre portfolio crypto. Suivez Bitcoin, Ethereum, BNB et 15+ cryptos. Calcul profit/perte automatique, visualisation performance, export CSV.",
    url: "/tracker-crypto",
    type: "website",
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return children;
}
